const MISAResouce = {
    vi: {
        // Employee
        Employee: "Nhân viên",
        AddNewEmployee: "Thêm",
        EmployeeCode: "Mã nhân viên",
        FullName: "Tên nhân viên",
        Gender: "Giới tính",
        DateOfBirth: "Ngày sinh",
        IdentityNumber: "Số CMND",
        PositionName: "Chức danh",
        DepartmentName: "Tên đơn vị",
        BankAccount: "Số tài khoản",
        BankName: "Tên ngân hàng",
        BankBranch: "Chi nhánh TK ngân hàng",

        // Feature
        Feature: "Chức năng",
        Fix: "Sửa",
        Show: "Xem",
        Duplicate: "Nhân bản",
        StopUsing: "Ngừng sử dụng",
        Using: "Đang sử dụng",
        Delete: "Xoá",
        Merge: "Gộp",

        // Record
        TotalNumber: "Tổng số",
        Record: "bản ghi",
        Total: "Tổng",

        // Error message
        ErrorEmpty: " không được để trống",
        ErrorInvalid: " không đúng định dạng",
        ErrorDate: " không được lớn hơn hiện tại!",
        ErrorEmail: " không đúng định dạng",
        ErrorNotNumber: " không phải là số, vui lòng nhập lại là số",
        ErrorNotText: " không phải là chữ, vui lòng nhập lại là chữ",

        // Paging
        Previous: "Trước",
        Next: "Sau",
        RecordInPage: "bản ghi trên 1 trang",

        //placehoder
        TxtSearch: "Tìm kiếm",
        TxtSearchAccount: "Tìm kiếm theo số, tên tài khoản",
        TxtConditionFilter: "Nhập giá trị lọc",
        Filter: "Lọc",
        Unfiltered: "Bỏ lọc",
        Contain: "Chứa",
        FixThisColumn: "Cố định cột này",

        //Sidebar
        Overview: "Tổng quan",
        Cash: "Tiền mặt",
        Banking: "Tiền gửi",
        Buy: "Mua hàng",
        Sales: "Bán hàng",
        InvoiceManaging: "Quản lí hoá đơn",
        Store: "Kho",
        Equipments: "Công cụ dụng cụ",
        FixedAssets: "Tài sản cố định",
        Tax: "Thuế",
        CostOfProduction: "Giá thành",
        General: "Tổng hợp",
        Budget: "Ngân sách",
        Report: "Báo cáo",
        FinancialAnalysis: "Phân tích tài chính",
        QuickAdd: "Thêm nhanh",

        // tooltip
        TooltipIdentityNumber: "Số chứng minh nhân dân",
        TooltipPhoneNumber: "Điện thoại di động",
        TooltipFixPhoneNumber: "Điện thoại cố định",
        TooltipHelp: "Giúp",
        TooltipClose: "Đóng (ESC)",
        TooltipSave: "Cất (ctrl + s)",
        TooltipSaveAndAdd: "Cất và thêm (ctrl + shift + s)",
        TooltipReload: "Lấy lại dữ liệu",
        TooltipExport: "Xuất ra Excel",
        TooltipCustomizeInterface: "Tùy chỉnh giao diện",
        ImplicitSampling: "Lấy mẫu ngầm định",

        // popup
        Enter: "Nhập",
        EmployeeInfo: "Thêm mới nhân viên",
        EditEmployeeInfo: "Sửa nhân viên",
        DuplicateEmployeeInfo: "Nhân bản nhân viên",
        Customer: "Là khách hàng",
        supplier: "Là nhà cung cấp",
        LabelEmployeeCode: "Mã",
        LabelEmployeeName: "Tên",
        LabelDepartmentName: "Đơn vị",
        LabelJobTitle: "Chức danh",
        LabelDateOfBirth: "Ngày sinh",
        LabelGender: "Giới tính",
        LabelMale: "Nam",
        LabelFemale: "Nữ",
        LabelOther: "Khác",
        LabelIdentityNumber: "Số CMND",
        LabelIdentityDate: "Ngày cấp",
        LabelIdentityPlace: "Nơi cấp",
        LabelAddress: "Địa chỉ",
        LabelPhoneNumber: "ĐT di động",
        LabelLandlineNumber: "ĐT cố định",
        LabelEmail: "Email",
        LabelBankAccount: "Tài khoản ngân hàng",
        LabelBankName: "Tên ngân hàng",
        LabelBankBranch: "Chi nhánh",

        // button
        BtnDestroy: "Hủy",
        BtnYes: "Có",
        BtnDestroyDialog: "Không",
        BtnDeleteDialog: "Xóa",
        BtnNo: "Không",
        BtnSaveEndAdd: "Cất và thêm",
        BtnSave: "Cất",
        BtnClose: "Đóng",
        BtnDeleteAll: "Xóa tất cả",
        BtnSaveData: "Lưu",
        BtnNoSave: "Không lưu",
        batchExecution: "Thực hiện hàng loạt",

        // title dialog
        DialogNotifyError: "Thông báo lỗi",
        DialogNotify: "Thông báo",
        DialogWarning: "Cảnh báo",
        MessageNotify: "Dữ liệu đã thay đổi. Bạn có muốn cất không?",
        MessageWarning: "Bạn có muốn xóa nhân viên ",
        MessageWarningMul: "Bạn có muốn xóa tất cả nhân viên được chọn",
        TxtNo: "không",

        // toast
        ToastAddSuccess: "Nhân viên đã được thêm",
        ToastDeleteSuccess: "Nhân viên đã bị xóa",
        ToastEditSuccess: "Nhân viên đã được sửa",
        ToastDuplicateSuccess: "Nhân viên đã được nhân bản",
        ToastTitleSuccess: "Thành công",

        // checkbox
        SelectedCheckbox: "Đã chọn: ",
        UndoSelected: "Bỏ chọn",
        SelectAllPage: "Chọn tất cả các trang",

        NoData: "Không dữ liệu",
        DataColumnName: "Tên cột dữ liệu",
        FixColumn: "Sửa tên cột hiển thị và độ rộng",
        ShowMore: "Hiển thị thêm",
        ColNameOnInterface: "Tên cột trên giao diện",
        ColWidth: "Độ rộng",
        FixedCol: "Cố định cột",

        //navbar cash
        Process: "Quy trình",
        Payment: "Chi tiền",
        ReceiveMoney: "Thu tiền",
        Stocktaking: "Kiểm kê",
        CashFlowForecast: "Dự báo dòng tiền",
        Export: "Báo cáo",

        // contextMenu
        Empty: "Trống",
        NotEmpty: "(Không trống)",
        Equal: "Bằng",
        Other: "Khác",
        NotContain: "Không chứa",
        StartWith: "Bắt đầu với",
        EndWith: "Kết thúc với",
        LessThan: "Nhỏ hơn",
        LessThanOrEqual: "Nhỏ hơn hoặc bằng",
        GreaterThan: "Lớn hơn",
        GreaterThanOrEqual: "Lớn hơn hoặc bằng",
        DeleteConditionFilter: "Xóa điều kiện lọc",

        // cash
        CashBusiness: "Nghiệp vụ tiền mặt",
        AccountSystem: "Hệ thống tài khoản",
        CustomerCash: "Khách hàng",
        Provider: "Nhà cung cấp",
        Option: "Tùy chọn",

        // accountSysterm
        AddNewAccount: "Thêm tài khoản",
        Extend: "Mở rộng",
        AccountNumber: "Số tài khoản",
        AccountName: "Tên tài khoản",
        Property: "Tính chất",
        EnglishName: "Tên tiếng anh",
        Interpret: "Diễn giải",
        Status: "Trạng thái",
        Debt: "Dư nợ",
        ExcessYes: "Dư có",
        Hermaphrodite: "Lưỡng tính",
        Nobalance: "Không có số dư",

        // popup Account
        LabelAccountNumber: "Số tài khoản",
        LabelAccountName: "Tên tài khoản",
        LabelEnglishName: "Tên tiếng anh",
        LabelGeneralAccount: "Tài khoản tổng hợp",
        LabelProperty: "Tính chất",
        LabelInterpret: "Diễn giải",
        ForeignCurrencyPlan: "Có hạch toán ngoại tệ",
        Object: "Đối tượng",
        followDetail: "Theo dõi chi tiết theo",

        //table payment
        AddNewPayment: "Chi tiền",
        AccountingDate: "Ngày hạch toán",
        DayVouchers: "Ngày chứng từ",
        NumberVouchers: "Số chứng từ",
        AmountOfMoney: "Số tiền",
        ObjectCode: "Mã đối tượng",
        Address: "Địa chỉ",
        Detail: "Chi tiết",
        DebitAccount: "TK nợ",
        CreditAccount: "TK có",
        ObjectName: "Tên đối tượng",

        //other
        Username: "Ngô Trung Kiên",
        MyCompany: "công ty tnhh sản xuất - thương mại - dịch vị qui phúc",
    },
    en: {
        // Employee
        Employee: "Employee",
        AddNewEmployee: "Add",
        EmployeeCode: "Employee code",
        FullName: "Employee name",
        Gender: "Gender",
        DateOfBirth: "Date of birth",
        IdentityNumber: "Identity number",
        PositionName: "Position Name",
        DepartmentName: "Department name",
        BankAccount: "Bank account",
        BankName: "Bank name",
        BankBranch: "Bank branch",

        // Feature
        Feature: "Feature",
        Fix: "Edit",
        Show: "Show",
        Duplicate: "Duplicate",
        StopUsing: "Stop using",
        Using: "Using",
        Delete: "Delete",
        Merge: "Merge",

        // Record
        TotalNumber: "Total number",
        Record: "records",
        Total: "Total",

        // Error message
        ErrorEmpty: " cannot be left blank, please re-enter",
        ErrorInvalid: " cannot format, please re-enter",
        ErrorDate: " isn't greater than current!",
        ErrorNotNumber: " not a number, please re-enter",
        ErrorNotText: " not the word, please re-enter",
        ErrorEmail: " Incorrect format",

        // Paging
        Previous: "Previous",
        Next: "Next",
        RecordInPage: "Records in a page",

        //placehoder
        TxtSearch: "Search",
        TxtSearchAccount: "Search by number, account name",
        TxtConditionFilter: "Enter filter value",
        Filter: "Filter",
        Unfiltered: "Unfiltered",
        Contain: "Contain",
        FixThisColumn: "Fix this column",
        FilterCondition: "Lọc Tên nhân viên",

        //Sidebar
        Overview: "Overview",
        Cash: "Cash",
        Banking: "Banking",
        Buy: "Buy",
        Sales: "Sales",
        InvoiceManaging: "Invoice managing",
        Store: "Store",
        Equipments: "Equipments",
        FixedAssets: "Fixed assets",
        Tax: "Tax",
        CostOfProduction: "Cost of production",
        General: "General",
        Budget: "Budget",
        Report: "Report",
        FinancialAnalysis: "Financial analysis",
        QuickAdd: "Quick add",

        // popup
        EmployeeInfo: "Add new employee",
        EditEmployeeInfo: "Edit employee infomation",
        DuplicateEmployeeInfo: "Employee duplicate",
        Customer: "Is a customer",
        supplier: "Is a supplier",
        LabelEmployeeCode: "ID",
        LabelEmployeeName: "Name",
        LabelDepartmentName: "Department",
        LabelJobTitle: "Job title",
        LabelDateOfBirth: "Date of birth",
        LabelGender: "Gender",
        LabelMale: "Male",
        LabelFemale: "Female",
        LabelOther: "Other",
        LabelIdentityNumber: "Identity Number",
        LabelIdentityDate: "Identity date",
        LabelIdentityPlace: "Identity place",
        LabelAddress: "Address",
        LabelPhoneNumber: "Phone number",
        LabelLandlineNumber: "Landline Number",
        LabelEmail: "Email",
        LabelBankAccount: "Bank account",
        LabelBankName: "Bank name",
        LabelBankBranch: "Bank branch",

        TooltipIdentityNumber: "Identity number",
        TooltipPhoneNumber: "Phone number",
        TooltipFixPhoneNumber: "Landline number",
        TooltipHelp: "Help",
        TooltipClose: "Close (ESC)",
        TooltipSave: "Save (ctrl + s)",
        TooltipSaveAndAdd: "Save and add (ctrl + shift + s)",
        TooltipReload: "Data recovery",
        TooltipExport: "Export excel",
        TooltipCustomizeInterface: "Customize interface",
        ImplicitSampling: "Implicit sampling",

        // button
        BtnDestroy: "Destroy",
        BtnSaveEndAdd: "Save and add",
        BtnDestroyDialog: "No",
        BtnDeleteDialog: "Delete",
        BtnSave: "Save",
        BtnClose: "Close",
        BtnYes: "Yes",
        BtnNo: "No",
        BtnDeleteAll: "Delete all",
        BtnSaveData: "Save",
        BtnNoSave: "Don't save",
        batchExecution: "batch execution",

        // title dialog
        DialogNotifyError: "Error! ",
        DialogWarning: "Warning",
        DialogNotify: "Notification",

        MessageNotify: "Data has changed. Do you want to save it?",
        MessageWarning: "Do you want to delete an employee ",
        MessageWarningMul: "Do you want to delete all selected employees ",
        TxtNo: "no",

        // toast
        ToastAddSuccess: "Staff has been added",
        ToastDeleteSuccess: "Employee has been deleted",
        ToastEditSuccess: "Staff has been edited",
        ToastDuplicateSuccess: "Staff has been duplicated",
        ToastTitleSuccess: "Success",

        NoData: "No data",
        DataColumnName: "Data column name",
        FixColumn: "Fix display column name and width",
        ShowMore: "Show more",
        ColNameOnInterface: "Column names on interface",
        ColWidth: "Width",
        FixedCol: "Fixed column",

        //navbar cash
        Process: "Progress",
        Payment: "Payment",
        ReceiveMoney: "Receive money",
        Stocktaking: "StockTaking",
        CashFlowForecast: "Cash flow forecast",
        Export: "Export",

        // contextMenu
        Empty: "Empty",
        NotEmpty: "(NotEmpty)",
        Equal: "Equal",
        Other: "Other",
        NotContain: "Not contain",
        StartWith: "Start with",
        EndWith: "End With",
        LessThan: "Less than",
        LessThanOrEqual: "Less than or equal",
        GreaterThan: "Greater than",
        GreaterThanOrEqual: "Greater than or equal",
        DeleteConditionFilter: "Delete condition filter",

        // cash
        CashBusiness: "Cash Business",
        AccountSystem: "Account systerm",
        CustomerCash: "Customer",
        Provider: "Provider",
        Option: "Options",
        Extend: "Extend",
        AddNewAccount: "Add account",
        AccountNumber: "Account number",
        AccountName: "Account name",
        Property: "Property",
        EnglishName: "English name",
        Interpret: "Interpret",
        Status: "Status",
        Debt: "Debt",
        ExcessYes: "Excess yes",
        Hermaphrodite: "Hermaphrodite",
        Nobalance: "No balance",

        // popup account
        LabelAccountNumber: "Account number",
        LabelAccountName: "Account name",
        LabelEnglishName: "English name",
        LabelGeneralAccount: "General account",
        LabelProperty: "Property",
        LabelInterpret: "Interpret",
        ForeignCurrencyPlan: "Have a foregin currency plan",
        Object: "Object",
        followDetail: "Track tracking details",

        // checkbox
        SelectedCheckbox: "selected: ",
        UndoSelected: "Undo Selected",
        SelectAllPage: "Selete all page",

        //table payment
        AddNewPayment: "Payment",
        AccountingDate: "Accounting date",
        DayVouchers: "Day vouchers",
        NumberVouchers: "Number vouchers",
        AmountOfMoney: "Amount of money",
        ObjectCode: "Object code",
        Address: "Address",
        Detail: "Detail",
        DebitAccount: "Debit account",
        CreditAccount: "Credit account",
        ObjectName: "Object name",

        //other
        Username: "Kien Ngo Trung",
        MyCompany: "Quy Phuc Production - Trading - Service",
    },
};
export default MISAResouce;
